### ISSUE TITLE
add ability to switch sides of captured/loaded images (probably by swiping)

### ISSUE THREAD

**Issue by KRA2008** [KRA2008/crosscam#112]

**Comment by Wursthub** [comment]
Had this feature request as well! Very useful if images are acquired by different camera and stitched in crosscam

**Comment by KRA2008** [comment]
Hey @Wursthub I've added this. Please try it out in the new version here and let me know how it goes: https://install.appcenter.ms/users/kra3030/apps/crosscam-1/distribution_groups/testers

**Comment by Wursthub** [comment]
Works like a charm! Supercool, good job!

However (you know, fixed a bug, found another):
If i import some vertical images they get rotated upon import. Can send the
originals in case you want to reproduce.
I know this is not a core-feature as most people will use the phonecam,
however wanted to point it out.
Attached see import workflow and result during alignment.

**Comment by KRA2008** [comment]
@Wursthub I don't see any attached images, and yeah having them would help me sort it out for sure.

I also wanted to suggest you go ahead and download the new version I put in the store this morning because I fixed a few other minor issues.

**Comment by KRA2008** [comment]
@Wursthub it says you made your reply through email - I think when you did that it dropped the attachments. If you make your reply right in github I'll be able to get attachments.

**Comment by Wursthub** [comment]
https://drive.google.com/folderview?id=1-rVB2hlek-PmBeUofw_eKKAPi8XGqAd6
Once im in wifi the files will appear here.

Cool to know someone capable who is similarily enthusiastic about this topic :)
