### ISSUE TITLE
Turn off shutter sound on certain particular Androids

### ISSUE THREAD

**Issue by JanGross** [KRA2008/crosscam#55]
The default shutter sound is loud and annoying.
My camera app has an option to disable it, but it doesn't seem to affect other apps.
Turning on "total silence mode" doesn't help either.

Would it be possible to make a "shutter sound" switch?

**Comment by KRA2008** [comment]
Hey, you're the first person (other than me) to engage with the Github project in any way. Welcome! May I ask how you came upon the project/app? Are you one of my Reddit testers?

Thanks for the feedback, sounds like a great idea. I always have my phone on silent mode so I forgot about this.

Would you agree with the default being "shutter sound" off?

**Comment by KRA2008** [comment]
Haha, that Reddit post was actually not supposed to happen... I mean I'm glad it let you find the app though! I had made a couple posts asking about testers for the app, and I had asked the testers who responded to that post to download the app and give me feedback but NOT to make any posts about it themselves, so as to keep it a secret for now, but then that user went ahead and made a post.

I'm working on some great stuff right now and I was hoping I would not get a large wave of interest until some more of this stuff is done.

**Comment by JanGross** [comment]
If I knew how this stuff works, I'd contribute. But I've never looked into app development that much.
Does this use some framework? Are there instructions on how to build this?

**Comment by KRA2008** [comment]
It is based around Xamarin.Forms so you'd need Visual Studio with Xamarin installed. Unfortunately I don't have contribution instructions yet.

**Comment by KRA2008** [comment]
In looking into this I'm remembering that I've researched it several times before and found this to be problematic on iOS. There is definitely no pretty way to get it done, and going with some of the ugly ways could get you punished in the store.

I think my approach might be just to leave the sound disabled for Android always and leave the iOS sound alone (regulated by volume/silent mode/geographic region).

When you say 
> My camera app has an option to disable it, but it doesn't seem to affect other apps.
What is the camera app you are describing? Native camera? Are you on Android or iOS?

**Comment by JanGross** [comment]
I'm on Android, not stock though. (Lenovo PB2-690M)

**Comment by KRA2008** [comment]
I've actually got code in place to mute the shutter on Android which seems to work on my test phones. What is the camera app you say you _aren't_ hearing the shutter sound in? Just the native vanilla camera?

**Comment by JanGross** [comment]
The Camera app definitely isn't stock either.
What Android version are your devices running?
I'm on Android v. 6.0.1 - API level 23

**Comment by KRA2008** [comment]
I have the following Android devices:
Galaxy S3, 4.4.2 - API Level 19
Nexus 4, 5.1.1 - API Level 22
Galaxy S9, 8.1.0 - API Level 27

But I have a hunch the problem is about the particular manufacturer more than it is the Android version. Is this other camera app you're using open-source by chance? I could peak at the source and see what they're doing to get this fixed for you.

**Comment by JanGross** [comment]
Unfortunately my research did not yield any useful results.  
The app is not open source nor did I have any luck decompiling it.  
I guess I'll have to live with the shutter sound

**Comment by KRA2008** [comment]
implementing #74 may accomplish this

**Comment by KRA2008** [comment]
@JanGross hey dude camera2 is live in the store. Please try it out and let me know if this fixed the sound issue for you.

**Comment by JanGross** [comment]
Hey @KRA2008, I just tested on the phone I used originally and the sound seems to be gone. :)
